# Generated by Django 3.2.9 on 2021-11-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='have',
            old_name='haver',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='want',
            old_name='wanter',
            new_name='user',
        ),
    ]
