# Generated by Django 3.2.9 on 2021-11-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIM', '0002_auto_20211111_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='have',
            name='icon_url',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='have',
            name='item_name',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='icon_url',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='item_name',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
